### ISSUE TITLE
SubtleCrypto fails to recognise some `CryptoKey`s

### ISSUE THREAD

**Issue by gnarea** [PeculiarVentures/webcrypto-core#55]
The following is failing for me:

https://github.com/PeculiarVentures/webcrypto-core/blob/22c0f0baeda86a22e9708eb831db015a3fceb827/src/subtle.ts#L244-L248

```
Error: Error during exporting public key: Key is not of type 'CryptoKey'

    at PublicKeyInfo.importKey (/home/gus/repos/relaynet-internet-gateway/node_modules/@relaycorp/relaynet-core/node_modules/pkijs/build/index.js:3935:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Function.issue (/home/gus/repos/relaynet-internet-gateway/node_modules/@relaycorp/relaynet-core/src/lib/crypto_wrappers/x509/Certificate.ts:108:5)
    at PublicGatewayManager.generate (/home/gus/repos/relaynet-internet-gateway/src/node/PublicGatewayManager.ts:40:32)
    at Object.<anonymous> (/home/gus/repos/relaynet-internet-gateway/src/node/PublicGatewayManager.spec.ts:67:28)
```

But it shouldn't be (according to my debugger):

![cryptokey-err](https://user-images.githubusercontent.com/369863/174647962-df4ef6be-7382-45fd-b6c8-4a07232d3d7b.png)

---

I think the issue is analogous to https://github.com/PeculiarVentures/asn1-schema/issues/71. Here some info on the dependency tree:

```
$ npm list webcrypto-core
@relaycorp/relaynet-internet-gateway@1.0.0 /home/gus/repos/relaynet-internet-gateway
└─┬ @relaycorp/relaynet-core@1.80.2
  ├─┬ @peculiar/webcrypto@1.4.0
  │ └── webcrypto-core@1.7.5  deduped
  └── webcrypto-core@1.7.5 

$ npm list @peculiar/webcrypto
@relaycorp/relaynet-internet-gateway@1.0.0 /home/gus/repos/relaynet-internet-gateway
└─┬ @relaycorp/relaynet-core@1.80.2
  └── @peculiar/webcrypto@1.4.0
```

The `CryptoKeyPair` is generated inside `@relaycorp/relaynet-core`, using `@peculiar/webcrypto`, and the resulting key pair is then passed to the root package (`relaynet-internet-gateway`). Then the root package tries to use that key pair to issue a self-signed certificate using `@relaycorp/relaynet-core` (which in turn uses PKI.js), but it fails with the error above.

Note that I tried skipping the `key instanceof CryptoKey` check above, but hit a new error from `@peculiar/webcrypto`:

```
Error: Error during exporting public key: Cannot get CryptoKey from secure storage

    at PublicKeyInfo.importKey (/home/gus/repos/relaynet-internet-gateway/node_modules/@relaycorp/relaynet-core/node_modules/pkijs/build/index.js:3935:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Function.issue (/home/gus/repos/relaynet-internet-gateway/node_modules/@relaycorp/relaynet-core/src/lib/crypto_wrappers/x509/Certificate.ts:108:5)
    at PublicGatewayManager.generate (/home/gus/repos/relaynet-internet-gateway/src/node/PublicGatewayManager.ts:40:32)
    at Object.<anonymous> (/home/gus/repos/relaynet-internet-gateway/src/node/PublicGatewayManager.spec.ts:67:28)
```

**Comment by microshine** [comment]
`@peculiar/webcrypto` use `WeakMap` to protect private key data. Here is [storage implementation](https://github.com/PeculiarVentures/webcrypto/blob/6b304aedf4920f0dfe6bb6504648d1e17948e195/src/mechs/storage.ts). As you can see, `getCryptoKey` throws `Cannot get CryptoKey from secure storage` exception.

Sometimes I've got the similar problem with `WebCrypto`. To fix it, I use `resolutions` option in `package.json` for `yarn`. Try to use [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) option for npm.

One more thought, maybe it's possible to fix the problem by moving `@peculiar/webcrypto` into `peerDependency`

**Comment by gnarea** [comment]
Hi @microshine! Thanks for looking into this.

What should I try setting `overrides` to in `package.json`? We're already using `webcrypto-core@1.7.5` across the board.

I tried adding `@peculiar/webcrypto` to `peerDependencies` in `@relaycorp/relaynet-core`. That makes `key instanceof CryptoKey` work, but then I hit the `WeakMap`-related issue:

```
Error: Error during exporting public key: Key is not of type 'CryptoKey'

    at PublicKeyInfo.importKey (/home/gus/repos/relaynet-internet-gateway/node_modules/@relaycorp/relaynet-core/node_modules/pkijs/build/index.js:3935:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Function.issue (/home/gus/repos/relaynet-internet-gateway/node_modules/@relaycorp/relaynet-core/src/lib/crypto_wrappers/x509/Certificate.ts:108:5)
    at PublicGatewayManager.generate (/home/gus/repos/relaynet-internet-gateway/src/node/PublicGatewayManager.ts:40:32)
    at Object.<anonymous> (/home/gus/repos/relaynet-internet-gateway/src/node/PublicGatewayManager.spec.ts:67:28)
```

I don't know why I'm hitting this issue, having seen the `@peculiar/webcrypto` implementation. It should work 🤔  I'll take another look at this tomorrow with fresh eyes.

**Comment by microshine** [comment]
Looks I was wrong. It's the same dependency for `@relaycorp/relaynet-core` package.

One more thought. Try to remove `package-lock.json` and `node_modules` folder and reinstall dependencies.

The structure of `node_modules` has been changed

<img width="327" alt="image" src="https://user-images.githubusercontent.com/7333669/175039029-f17d7f4a-7362-45a3-9ee6-4970011a1c80.png">

**Comment by gnarea** [comment]
Thanks @microshine!

I've now [added `@peculiar/webcrypto` and `webcrypto-core` (for good measure) to `@relaycorp/relaynewt-core`](https://github.com/relaycorp/relaynet-core-js/blob/02204e256e8b4b9743713c1296c1cc53463676ca/package.json#L59-L60), and re-created `package-lock.json` in `relaynet-internet-gateway`. However, this last change appears to have taken me back to the original problem of `Key is not of type 'CryptoKey'`.

Note that this time `npm list` does show a single instance of `@peculiar/webcrypto`:

```
$ npm list @peculiar/webcrypto
@relaycorp/relaynet-internet-gateway@1.0.0 /home/gus/repos/relaynet-internet-gateway
└─┬ @relaycorp/relaynet-core@1.81.2
  └── @peculiar/webcrypto@1.4.0
```
